on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - synchronize
      - reopened

name: Build Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: NPM Build
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test --if-present
    - run: npm run build --if-present

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

